### ISSUE TITLE
IODD & PIN

### ISSUE THREAD

**Issue by Paulart1977** [unref-ptr/lwIOLink#1]
Hello,
I would like to try your project but I have some issues.
First, could you add a iodd file with the project to try it more easily ?
Moreover on which pin do you plug your io-link's wire on the arduino uno (I think i plug it wright but just in case)?
thanks in advance

**Comment by 0x6D70** [comment]
For connecting the IO-Link wire to the Arduino you need an IO-Link transceiver. For example the LT3669 transciever, which is mentioned in the README. The IO-Link transceiver is connected to the arduino and you can set the Pins using the ``HwConfig`` class. Have a look at the example: [Hardware Config example](https://github.com/unref-ptr/lwIOLink/blob/61c31a0dedf91370d27eb8d888f47944b51dbdb7/examples/lwIOLink_Demo/lwIOLink_Demo.ino#L30)
